### ISSUE TITLE
EmojiOne SVG Zip No Longer Free

### ISSUE THREAD

**Issue by thenickot2** [NodeBB-Community/nodebb-plugin-emoji-one#9]
Archive file in the plugin is http://emojione.com/wp-content/uploads/assets/e1-svg.zip which results in a 404. It appears the svgs for EmojiOne now require a premium account https://www.emojione.com/developers/download

**Comment by pitaj** [comment]
> Archive file in the plugin is http://emojione.com/wp-content/uploads/assets/e1-svg.zip

[No, it does not](https://github.com/NodeBB-Community/nodebb-plugin-emoji-one/blob/master/lib/set/update/main.js#L14)

You must be on an old version of the plugin.
